name: Generate Snake

on:
  schedule: # Run every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual run
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: DPG746
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push generated snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
